Added RDF namespace for @rdf:resource in aggregations.
Links are broken:
java.io.IOException: [textgrid:2kgv2] Missing aggregation reference: ../../../transcript/fdh_frankfurt/Hs-6626/Hs-6626_5.xml